language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip install requests
 - pip install nose
 - pip install mixpanel-py
# command to run tests, e.g. python setup.py test
script:  nosetests --nocapture
notifications:
  email:
    on_success: never
    on_failure: always
