language: python
python:
  # https://endoflife.date/python
  # goes away in sep 2020
  - "3.5"
  # goes away in dec 2021
  - "3.6"
  # goes away in jun 2023
  - "3.7"
  # goes away in oct 2024
  - "3.8"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install requests
 - pip install nose
 - pip install coverage
 - pip install coveralls
# command to run tests, e.g. python setup.py test
script: coverage run --source=hackertray $(which nosetests)
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: always
